name: release

on:
  repository_dispatch:
    types:
      - update_repo

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  WORK_DIR: ./data/work/
  REPO:      ${{ github.event.client_payload.repo }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Checkout dev
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: dev

      - name: Setup Python
        uses: actions/setup-python@v1

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Get repository date
        run: |
          mkdir -p ${{ env.WORK_DIR }}
          gh repo view ${{ env.REPO }} --json name,nameWithOwner,description > ${{ env.WORK_DIR }}repo.json
          gh release view -R ${{ env.REPO }} --json tagName,body > ${{ env.WORK_DIR }}release.json
          gh api -H "Accept: application/vnd.github.raw" repos/G-alumi/SimutransPak128Japan-v-Gal_hanshin/contents/.github/REPO.json > .${{ env.WORK_DIR }}repo2.json

      - name: Run main.py
        run: |
          python main.py

      - name: Commit generated files to dev
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Botによるページ生成" || echo "No changes to commit"
          git push origin dev

      - name: Merge dev to main
        run: |
          git fetch origin main
          git checkout main
          git merge dev --no-ff -m "ページ公開"
          git push origin main