name: release

on:
  push:
    branches:
      - dev

jobs:
  build:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout dev
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: dev

      - name: Setup Python
        uses: actions/setup-python@v1

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run main.py
        run: |
          python main.py

      - name: Commit generated files to dev
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Botによるページ生成" || echo "No changes to commit"
          git push origin dev

      - name: Merge dev to main
        run: |
          git fetch origin main
          git checkout main
          git merge dev --no-ff -m "ページ公開"
          git push origin main